// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {tg} from '../models';
import {main} from '../models';

export function NewCmd(arg1:string,arg2:Array<string>):Promise<tg.Cmd>;

export function NewUpdate(arg1:string,arg2:tg.Cmd):Promise<main.Update>;

export function Send(arg1:main.Update):Promise<main.Response>;
