package constants

const (
	CmdShowStart          = "start"
	CmdDoNothing          = "nothing"
	CmdShowLater          = "later"
	CmdShowToday          = "today"
	CmdShowNotes          = "notes"
	CmdShowPostpone       = "postpone"
	CmdShowFiles          = "files"
	CmdShowRename         = "rename"
	CmdShowChecklists     = "checklists"
	CmdShowStats          = "stats"
	CmdComplete           = "comp"
	CmdPostpone           = "post"
	CmdRenameFile         = "rename_file"
	CmdShowMultilineTask  = "task"
	CmdShowFile           = "file"
	CmdShowChecklist      = "checklist"
	CmdShowChooseDay      = "to_day"
	CmdShowToFile         = "to_file"
	CmdShowToDoc          = "to_doc"
	CmdShowToChecklist    = "to_checklist"
	CmdMove               = "mv"
	CmdMoveToNewDir       = "mv_to_new_dir"
	CmdMoveToFile         = "mv_to_file"
	CmdMoveToNewDoc       = "mv_to_new_doc"
	CmdMoveToChecklist    = "mv_to_chk"
	CmdMoveToNewChecklist = "mv_to_new_chk"
	CmdMoveJournal        = "mv_to_journal"
	CmdSchedule           = "sc"
	CmdPomodoro           = "pomodoro"
	CmdShowRecurringKB    = "recur_kb"
	CmdTomorrow           = "tomorrow"
	CmdLater              = "later"
	CmdShowSettings       = "settings"
	CmdConfigurePanel     = "configure_panel"
	CmdAddToPanel         = "panel_add"
	CmdDelFromPonel       = "panel_del"
	CmdShowReadChecklist  = "read"
	CmdShowWatchChecklist = "watch"
	CmdShowShopChecklist  = "shop"

	CmdInlineQuerySearchEveryWhere = "search"
	CmdInlineQuerySearchInDir      = "search_dir"
	CmdWebAppHabits                = "habits"
)
