package constants

// Telegram only allows 64 bytes in callback_data,
// So we have to be really short :)
const (
	CmdShowStart          = "start"
	CmdDoNothing          = "nothing"
	CmdShowLater          = "later"
	CmdShowToday          = "today"
	CmdShowFiles          = "files"
	CmdShowPostpone       = "postpone"
	CmdShowRename         = "rename"
	CmdShowChecklists     = "checklists"
	CmdShowStats          = "stats"
	CmdComplete           = "c"
	CmdPostpone           = "post"
	CmdRenameFile         = "rename_file"
	CmdShowMultilineTask  = "task"
	CmdShowFile           = "file"
	CmdShowChecklist      = "checklist"
	CmdCompleteChecklist  = "cc"
	CmdShowMoveToFile     = "to_file"
	CmdShowToChecklist    = "to_checklist"
	CmdMoveToDir          = "mv"
	CmdMoveToNewDir       = "mv_to_new_dir"
	CmdMoveToExistingFile = "mf"
	CmdMoveToNewFile      = "mv_to_new_doc"
	CmdMoveToChecklist    = "mv_to_chk"
	CmdMoveToNewChecklist = "mv_to_new_chk"
	CmdMoveToJournal      = "mv_to_journal"
	CmdShowScheduleForDay = "sc_day"
	CmdSchedule           = "sc"
	CmdScheduleForTmrw    = "sc_tmrw"
	CmdPomodoro           = "pomodoro"
	CmdShowRecurringKB    = "recur_kb"
	CmdLater              = "later"
	CmdShowSettings       = "settings"
	CmdConfigurePanel     = "configure_panel"
	CmdAddToPanel         = "panel_add"
	CmdDelFromPonel       = "panel_del"
	CmdShowReadChecklist  = "read"
	CmdShowWatchChecklist = "watch"
	CmdShowShopChecklist  = "shop"

	CmdInlineQuerySearchEveryWhere = "search"
	CmdInlineQuerySearchInDir      = "search_dir"
	CmdWebAppHabits                = "habits"
)
